/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.zing.zingsbiomes.init;

import net.neoforged.neoforge.client.event.EntityRenderersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.resources.Identifier;
import net.minecraft.client.model.object.boat.BoatModel;
import net.minecraft.client.model.geom.ModelLayerLocation;

import com.zing.zingsbiomes.client.model.*;

@EventBusSubscriber(Dist.CLIENT)
public class ZingsBiomesModModels {
	public static final ModelLayerLocation KAPOK_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/kapok_boat"), "main");
	public static final ModelLayerLocation RED_DRIFTWOOD_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/red_driftwood_boat"), "main");
	public static final ModelLayerLocation DRIFTWOOD_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/driftwood_boat"), "main");
	public static final ModelLayerLocation ULTRAVIOLET_OAK_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/ultraviolet_oak_boat"), "main");
	public static final ModelLayerLocation BLACKWOOD_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/blackwood_boat"), "main");
	public static final ModelLayerLocation PALM_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/palm_boat"), "main");
	public static final ModelLayerLocation BAOBAB_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/baobab_boat"), "main");
	public static final ModelLayerLocation FIR_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/fir_boat"), "main");
	public static final ModelLayerLocation GRAZED_SPRUCE_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/grazed_spruce_boat"), "main");
	public static final ModelLayerLocation FROZEGROVE_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/frozegrove_boat"), "main");
	public static final ModelLayerLocation BLUEBERRY_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/blueberry_boat"), "main");
	public static final ModelLayerLocation MOSSBARK_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/mossbark_boat"), "main");
	public static final ModelLayerLocation KAPOK_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/kapok_boat_with_chest"), "main");
	public static final ModelLayerLocation RED_DRIFTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/red_driftwood_boat_with_chest"), "main");
	public static final ModelLayerLocation DRIFTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/driftwood_boat_with_chest"), "main");
	public static final ModelLayerLocation ULTRAVIOLET_OAK_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/ultraviolet_oak_boat_with_chest"), "main");
	public static final ModelLayerLocation BLACKWOOD_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/blackwood_boat_with_chest"), "main");
	public static final ModelLayerLocation PALM_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/palm_boat_with_chest"), "main");
	public static final ModelLayerLocation BAOBAB_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/baobab_boat_with_chest"), "main");
	public static final ModelLayerLocation FIR_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/fir_boat_with_chest"), "main");
	public static final ModelLayerLocation GRAZED_SPRUCE_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/grazed_spruce_boat_with_chest"), "main");
	public static final ModelLayerLocation FROZEGROVE_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/frozegrove_boat_with_chest"), "main");
	public static final ModelLayerLocation BLUEBERRY_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/blueberry_boat_with_chest"), "main");
	public static final ModelLayerLocation MOSSBARK_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/mossbark_boat_with_chest"), "main");
	public static final ModelLayerLocation SHAMROCK_WILLOW_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/shamrock_willow_boat"), "main");
	public static final ModelLayerLocation SHAMROCK_WILLOW_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/shamrock_willow_boat_with_chest"), "main");
	public static final ModelLayerLocation BLACKBERRY_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/blackberry_boat"), "main");
	public static final ModelLayerLocation BLACKBERRY_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/blackberry_boat_with_chest"), "main");
	public static final ModelLayerLocation GOOSEBERRY_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/gooseberry_boat"), "main");
	public static final ModelLayerLocation STRAWBERRY_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/strawberry_boat"), "main");
	public static final ModelLayerLocation RASPBERRY_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/raspberry_boat"), "main");
	public static final ModelLayerLocation GOLDENBERRY_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/goldenberry_boat"), "main");
	public static final ModelLayerLocation GLOW_BERRY_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/glow_berry_boat"), "main");
	public static final ModelLayerLocation SWEET_BERRY_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/sweet_berry_boat"), "main");
	public static final ModelLayerLocation GOOSEBERRY_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/gooseberry_boat_with_chest"), "main");
	public static final ModelLayerLocation STRAWBERRY_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/strawberry_boat_with_chest"), "main");
	public static final ModelLayerLocation RASPBERRY_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/raspberry_boat_with_chest"), "main");
	public static final ModelLayerLocation GOLDENBERRY_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/goldenberry_boat_with_chest"), "main");
	public static final ModelLayerLocation GLOW_BERRY_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/glow_berry_boat_with_chest"), "main");
	public static final ModelLayerLocation SWEET_BERRY_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/sweet_berry_boat_with_chest"), "main");
	public static final ModelLayerLocation SUNSHINE_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/sunshine_boat"), "main");
	public static final ModelLayerLocation HOARFROST_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/hoarfrost_boat"), "main");
	public static final ModelLayerLocation BLUE_DRIFTWOOD_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/blue_driftwood_boat"), "main");
	public static final ModelLayerLocation SUNSHINE_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/sunshine_boat_with_chest"), "main");
	public static final ModelLayerLocation HOARFROST_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/hoarfrost_boat_with_chest"), "main");
	public static final ModelLayerLocation BLUE_DRIFTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/blue_driftwood_boat_with_chest"), "main");
	public static final ModelLayerLocation WILLOW_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/willow_boat"), "main");
	public static final ModelLayerLocation HEARTWOOD_BOAT_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:boat/heartwood_boat"), "main");
	public static final ModelLayerLocation WILLOW_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/willow_boat_with_chest"), "main");
	public static final ModelLayerLocation HEARTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION = new ModelLayerLocation(Identifier.parse("zings_biomes:chest_boat/heartwood_boat_with_chest"), "main");

	@SubscribeEvent
	public static void registerLayerDefinitions(EntityRenderersEvent.RegisterLayerDefinitions event) {
		event.registerLayerDefinition(Modelsled.LAYER_LOCATION, Modelsled::createBodyLayer);
		event.registerLayerDefinition(Modelseaghast.LAYER_LOCATION, Modelseaghast::createBodyLayer);
		event.registerLayerDefinition(Modelseahorse.LAYER_LOCATION, Modelseahorse::createBodyLayer);
		event.registerLayerDefinition(Modelcaribou.LAYER_LOCATION, Modelcaribou::createBodyLayer);
		event.registerLayerDefinition(Modelender_cube.LAYER_LOCATION, Modelender_cube::createBodyLayer);
		event.registerLayerDefinition(Modeltuna.LAYER_LOCATION, Modeltuna::createBodyLayer);
		event.registerLayerDefinition(Modelglare.LAYER_LOCATION, Modelglare::createBodyLayer);
		event.registerLayerDefinition(Modelicy_spider.LAYER_LOCATION, Modelicy_spider::createBodyLayer);
		event.registerLayerDefinition(Modellog_flume.LAYER_LOCATION, Modellog_flume::createBodyLayer);
		event.registerLayerDefinition(Modelsunfish.LAYER_LOCATION, Modelsunfish::createBodyLayer);
		event.registerLayerDefinition(Modeltrout.LAYER_LOCATION, Modeltrout::createBodyLayer);
		event.registerLayerDefinition(Modelprarie_dog.LAYER_LOCATION, Modelprarie_dog::createBodyLayer);
		event.registerLayerDefinition(Modellynx.LAYER_LOCATION, Modellynx::createBodyLayer);
		event.registerLayerDefinition(Modelbomberry.LAYER_LOCATION, Modelbomberry::createBodyLayer);
		event.registerLayerDefinition(Modelmooshroom.LAYER_LOCATION, Modelmooshroom::createBodyLayer);
		event.registerLayerDefinition(Modelsquid.LAYER_LOCATION, Modelsquid::createBodyLayer);
		event.registerLayerDefinition(Modelkoi.LAYER_LOCATION, Modelkoi::createBodyLayer);
		event.registerLayerDefinition(Modeliguana.LAYER_LOCATION, Modeliguana::createBodyLayer);
		event.registerLayerDefinition(Modeljawfish.LAYER_LOCATION, Modeljawfish::createBodyLayer);
		event.registerLayerDefinition(Modeldeer.LAYER_LOCATION, Modeldeer::createBodyLayer);
		event.registerLayerDefinition(Modelemperor_penguin.LAYER_LOCATION, Modelemperor_penguin::createBodyLayer);
		event.registerLayerDefinition(Modelanglerfish.LAYER_LOCATION, Modelanglerfish::createBodyLayer);
		event.registerLayerDefinition(Modelarrow.LAYER_LOCATION, Modelarrow::createBodyLayer);
		event.registerLayerDefinition(Modelgraze.LAYER_LOCATION, Modelgraze::createBodyLayer);
		event.registerLayerDefinition(Modelwooden_birdzing_nether.LAYER_LOCATION, Modelwooden_birdzing_nether::createBodyLayer);
		event.registerLayerDefinition(Modelwooden_birdzing_bamboo.LAYER_LOCATION, Modelwooden_birdzing_bamboo::createBodyLayer);
		event.registerLayerDefinition(Modelbleatshroom_spit.LAYER_LOCATION, Modelbleatshroom_spit::createBodyLayer);
		event.registerLayerDefinition(Modelcoyote.LAYER_LOCATION, Modelcoyote::createBodyLayer);
		event.registerLayerDefinition(Modelsea_urchin.LAYER_LOCATION, Modelsea_urchin::createBodyLayer);
		event.registerLayerDefinition(Modelsurfboard.LAYER_LOCATION, Modelsurfboard::createBodyLayer);
		event.registerLayerDefinition(Modelwooden_birdzing_azalea.LAYER_LOCATION, Modelwooden_birdzing_azalea::createBodyLayer);
		event.registerLayerDefinition(Modelsardine.LAYER_LOCATION, Modelsardine::createBodyLayer);
		event.registerLayerDefinition(Modelsea_bunny.LAYER_LOCATION, Modelsea_bunny::createBodyLayer);
		event.registerLayerDefinition(Modelwooden_birdzing_end.LAYER_LOCATION, Modelwooden_birdzing_end::createBodyLayer);
		event.registerLayerDefinition(Modelmanta_ray.LAYER_LOCATION, Modelmanta_ray::createBodyLayer);
		event.registerLayerDefinition(Modelbleatshroom.LAYER_LOCATION, Modelbleatshroom::createBodyLayer);
		event.registerLayerDefinition(Modelpenguin.LAYER_LOCATION, Modelpenguin::createBodyLayer);
		event.registerLayerDefinition(Modelbutterfly.LAYER_LOCATION, Modelbutterfly::createBodyLayer);
		event.registerLayerDefinition(Modeldrenched_spider.LAYER_LOCATION, Modeldrenched_spider::createBodyLayer);
		event.registerLayerDefinition(Modelcreaking.LAYER_LOCATION, Modelcreaking::createBodyLayer);
		event.registerLayerDefinition(Modelflytrap_sea_anemone_entity_model.LAYER_LOCATION, Modelflytrap_sea_anemone_entity_model::createBodyLayer);
		event.registerLayerDefinition(Modeldragonfly.LAYER_LOCATION, Modeldragonfly::createBodyLayer);
		event.registerLayerDefinition(Modelcapybara.LAYER_LOCATION, Modelcapybara::createBodyLayer);
		event.registerLayerDefinition(Modelwooden_birdzing_woodland.LAYER_LOCATION, Modelwooden_birdzing_woodland::createBodyLayer);
		event.registerLayerDefinition(Modelmountaineer.LAYER_LOCATION, Modelmountaineer::createBodyLayer);
		event.registerLayerDefinition(Modelmeerkat.LAYER_LOCATION, Modelmeerkat::createBodyLayer);
		event.registerLayerDefinition(Modelgiraffe.LAYER_LOCATION, Modelgiraffe::createBodyLayer);
		event.registerLayerDefinition(Modelcaribou_armor.LAYER_LOCATION, Modelcaribou_armor::createBodyLayer);
		event.registerLayerDefinition(Modelzombie.LAYER_LOCATION, Modelzombie::createBodyLayer);
		event.registerLayerDefinition(Modelhippo.LAYER_LOCATION, Modelhippo::createBodyLayer);
		event.registerLayerDefinition(Modeltermite.LAYER_LOCATION, Modeltermite::createBodyLayer);
		event.registerLayerDefinition(Modelshrieker.LAYER_LOCATION, Modelshrieker::createBodyLayer);
		event.registerLayerDefinition(Modelblowdart.LAYER_LOCATION, Modelblowdart::createBodyLayer);
		event.registerLayerDefinition(Modelchorus_snail.LAYER_LOCATION, Modelchorus_snail::createBodyLayer);
		event.registerLayerDefinition(Modelsled_with_chest.LAYER_LOCATION, Modelsled_with_chest::createBodyLayer);
		event.registerLayerDefinition(Modelspidershroom.LAYER_LOCATION, Modelspidershroom::createBodyLayer);
		event.registerLayerDefinition(Modelguardian.LAYER_LOCATION, Modelguardian::createBodyLayer);
		event.registerLayerDefinition(Modellemur.LAYER_LOCATION, Modellemur::createBodyLayer);
		event.registerLayerDefinition(Modelzebra.LAYER_LOCATION, Modelzebra::createBodyLayer);
		event.registerLayerDefinition(Modeltuff_golem.LAYER_LOCATION, Modeltuff_golem::createBodyLayer);
		event.registerLayerDefinition(Modelultrabbit.LAYER_LOCATION, Modelultrabbit::createBodyLayer);
		event.registerLayerDefinition(Modelostrich.LAYER_LOCATION, Modelostrich::createBodyLayer);
		event.registerLayerDefinition(Modelwooden_birdzing_entity_model.LAYER_LOCATION, Modelwooden_birdzing_entity_model::createBodyLayer);
		event.registerLayerDefinition(Modelstarfish.LAYER_LOCATION, Modelstarfish::createBodyLayer);
		event.registerLayerDefinition(Modelcreaker.LAYER_LOCATION, Modelcreaker::createBodyLayer);
		event.registerLayerDefinition(Modelred_panda.LAYER_LOCATION, Modelred_panda::createBodyLayer);
		event.registerLayerDefinition(Modelfennec_fox.LAYER_LOCATION, Modelfennec_fox::createBodyLayer);
		event.registerLayerDefinition(Modelwither_skull.LAYER_LOCATION, Modelwither_skull::createBodyLayer);
		event.registerLayerDefinition(Modelduck.LAYER_LOCATION, Modelduck::createBodyLayer);
		event.registerLayerDefinition(Modelblack_bear.LAYER_LOCATION, Modelblack_bear::createBodyLayer);
		event.registerLayerDefinition(Modelmuskox.LAYER_LOCATION, Modelmuskox::createBodyLayer);
		event.registerLayerDefinition(Modelskeleton.LAYER_LOCATION, Modelskeleton::createBodyLayer);
		event.registerLayerDefinition(Modelbarreleye.LAYER_LOCATION, Modelbarreleye::createBodyLayer);
		event.registerLayerDefinition(Modelfire_salamander.LAYER_LOCATION, Modelfire_salamander::createBodyLayer);
		event.registerLayerDefinition(Modelpronghorn.LAYER_LOCATION, Modelpronghorn::createBodyLayer);
		event.registerLayerDefinition(Modelladybug.LAYER_LOCATION, Modelladybug::createBodyLayer);
		event.registerLayerDefinition(Modelspringtail.LAYER_LOCATION, Modelspringtail::createBodyLayer);
		event.registerLayerDefinition(Modelswan.LAYER_LOCATION, Modelswan::createBodyLayer);
		event.registerLayerDefinition(Modellightfish.LAYER_LOCATION, Modellightfish::createBodyLayer);
		event.registerLayerDefinition(Modelbadger.LAYER_LOCATION, Modelbadger::createBodyLayer);
		event.registerLayerDefinition(Modelwater_buffalo.LAYER_LOCATION, Modelwater_buffalo::createBodyLayer);
		event.registerLayerDefinition(Modelpiranha.LAYER_LOCATION, Modelpiranha::createBodyLayer);
		event.registerLayerDefinition(Modelsporeeper.LAYER_LOCATION, Modelsporeeper::createBodyLayer);
		event.registerLayerDefinition(Modelmoth.LAYER_LOCATION, Modelmoth::createBodyLayer);
		event.registerLayerDefinition(Modelwaves.LAYER_LOCATION, Modelwaves::createBodyLayer);
		event.registerLayerDefinition(Modelswordfish.LAYER_LOCATION, Modelswordfish::createBodyLayer);
		event.registerLayerDefinition(Modelvulture.LAYER_LOCATION, Modelvulture::createBodyLayer);
		event.registerLayerDefinition(Modeljellyfish.LAYER_LOCATION, Modeljellyfish::createBodyLayer);
		event.registerLayerDefinition(Modeltnt.LAYER_LOCATION, Modeltnt::createBodyLayer);
		event.registerLayerDefinition(Modelwitch.LAYER_LOCATION, Modelwitch::createBodyLayer);
		event.registerLayerDefinition(Modelshrimp.LAYER_LOCATION, Modelshrimp::createBodyLayer);
		event.registerLayerDefinition(Modelember_wither.LAYER_LOCATION, Modelember_wither::createBodyLayer);
		event.registerLayerDefinition(Modelelk.LAYER_LOCATION, Modelelk::createBodyLayer);
		event.registerLayerDefinition(Modelfly.LAYER_LOCATION, Modelfly::createBodyLayer);
		event.registerLayerDefinition(Modelboar.LAYER_LOCATION, Modelboar::createBodyLayer);
		event.registerLayerDefinition(Modelcreak_spider.LAYER_LOCATION, Modelcreak_spider::createBodyLayer);
		event.registerLayerDefinition(Modelwooden_birdzing_baby.LAYER_LOCATION, Modelwooden_birdzing_baby::createBodyLayer);
		event.registerLayerDefinition(KAPOK_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(RED_DRIFTWOOD_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(DRIFTWOOD_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(ULTRAVIOLET_OAK_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(BLACKWOOD_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(PALM_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(BAOBAB_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(FIR_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(GRAZED_SPRUCE_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(FROZEGROVE_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(BLUEBERRY_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(MOSSBARK_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(KAPOK_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(RED_DRIFTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(DRIFTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(ULTRAVIOLET_OAK_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(BLACKWOOD_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(PALM_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(BAOBAB_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(FIR_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(GRAZED_SPRUCE_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(FROZEGROVE_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(BLUEBERRY_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(MOSSBARK_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(SHAMROCK_WILLOW_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(SHAMROCK_WILLOW_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(BLACKBERRY_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(BLACKBERRY_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(GOOSEBERRY_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(STRAWBERRY_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(RASPBERRY_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(GOLDENBERRY_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(GLOW_BERRY_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(SWEET_BERRY_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(GOOSEBERRY_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(STRAWBERRY_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(RASPBERRY_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(GOLDENBERRY_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(GLOW_BERRY_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(SWEET_BERRY_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(SUNSHINE_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(HOARFROST_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(BLUE_DRIFTWOOD_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(SUNSHINE_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(HOARFROST_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(BLUE_DRIFTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(WILLOW_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(HEARTWOOD_BOAT_LAYER_LOCATION, BoatModel::createBoatModel);
		event.registerLayerDefinition(WILLOW_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
		event.registerLayerDefinition(HEARTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION, BoatModel::createChestBoatModel);
	}
}