/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.zingsbiomes.init;

import net.neoforged.neoforge.client.event.EntityRenderersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.client.renderer.entity.ThrownItemRenderer;
import net.minecraft.client.renderer.entity.BoatRenderer;

import net.mcreator.zingsbiomes.client.renderer.*;

@EventBusSubscriber(Dist.CLIENT)
public class ZingsBiomesModEntityRenderers {
	@SubscribeEvent
	public static void registerEntityRenderers(EntityRenderersEvent.RegisterRenderers event) {
		event.registerEntityRenderer(ZingsBiomesModEntities.SCORCHED.get(), ScorchedRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.TANGLED.get(), TangledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.THAWED.get(), ThawedRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.FLOOD_CREEPER.get(), FloodCreeperRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.NETHER_CREEPER.get(), NetherCreeperRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.VINE_CREEPER.get(), VineCreeperRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SNOW_CREEPER.get(), SnowCreeperRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SANDSTONE_CREEPER.get(), SandstoneCreeperRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.DRENCHED_SPIDER.get(), DrenchedSpiderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BURNED_SPIDER.get(), BurnedSpiderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.POISONED_SPIDER.get(), PoisonedSpiderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ICY_SPIDER.get(), IcySpiderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SANDY_SPIDER.get(), SandySpiderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SOUL_BURNED_SPIDER.get(), SoulBurnedSpiderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.WOODLAND_WOODEN_BIRDZING.get(), OakWoodenBirdzingRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.NETHER_WOODEN_BIRDZING.get(), CrimsonWoodenBirdzingRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BERRY_WOODEN_BIRDZING.get(), CherryWoodenBirdzingRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.WEEPING_WOODEN_BIRDZING.get(), PaleWoodenBirdzingRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BAMBOO_WOODEN_BIRDZING.get(), BambooWoodenBirdzingRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.KAPOK_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.KAPOK_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.RED_DRIFTWOOD_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.RED_DRIFTWOOD_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.DRIFTWOOD_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.DRIFTWOOD_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.ULTRAVIOLET_OAK_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.ULTRAVIOLET_OAK_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.BLACKWOOD_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BLACKWOOD_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.PALM_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.PALM_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.BAOBAB_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BAOBAB_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.FIR_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.FIR_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.GRAZED_SPRUCE_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.GRAZED_SPRUCE_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.FROZEGROVE_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.FROZEGROVE_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.BLUEBERRY_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BLUEBERRY_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.MOSSBARK_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.MOSSBARK_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.KAPOK_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.KAPOK_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.RED_DRIFTWOOD_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.RED_DRIFTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.DRIFTWOOD_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.DRIFTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.ULTRAVIOLET_OAK_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.ULTRAVIOLET_OAK_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.BLACKWOOD_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BLACKWOOD_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.PALM_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.PALM_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.BAOBAB_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BAOBAB_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.FIR_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.FIR_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.GRAZED_SPRUCE_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.GRAZED_SPRUCE_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.FROZEGROVE_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.FROZEGROVE_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.BLUEBERRY_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BLUEBERRY_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.MOSSBARK_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.MOSSBARK_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.SHAMROCK_WILLOW_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.SHAMROCK_WILLOW_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.SHAMROCK_WILLOW_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.SHAMROCK_WILLOW_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.INVERTED_SHAMROCK_COW.get(), InvertedShamrockCowRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SHAMROCK_COW.get(), ShamrockCowRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.FENNEC_FOX.get(), FennecFoxRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.PRONGHORN.get(), PronghornRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MEERKAT.get(), MeerkatRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.COYOTE.get(), CoyoteRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.PRARIE_DOG.get(), PrarieDogRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.VULTURE.get(), VultureRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.HIPPO.get(), HippoRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.GIRAFFE.get(), GiraffeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ZEBRA.get(), ZebraRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.TERMITE.get(), TermiteRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.OSTRICH.get(), OstrichRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.DRAGONFLY.get(), DragonflyRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BLACK_BEAR.get(), BlackBearRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.PIRANHA.get(), PiranhaRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.FLY.get(), FlyRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ELK.get(), ElkRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CARIBOU.get(), CaribouRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.LYNX.get(), LynxRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.DUCK.get(), DuckRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SWAN.get(), SwanRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MUSKOX.get(), MuskoxRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.LADYBUG.get(), LadybugRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MOUNTAINEER.get(), MountaineerRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.WATER_BUFFALO.get(), WaterBuffaloRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CARIBOU_STRAY.get(), CaribouStrayRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SPRUCE_LOG_FLUME.get(), SpruceLogFlumeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SPRUCE_SLED.get(), SpruceSledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SARDINE.get(), SardineRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SEA_URCHIN.get(), SeaUrchinRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SEAGHAST.get(), SeaghastRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.STARFISH.get(), StarfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SHRIMP.get(), ShrimpRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.JELLYFISH.get(), JellyfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.LIGHTFISH.get(), LightfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BARRELEYE.get(), BarreleyeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.JAWFISH.get(), JawfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SEAHORSE.get(), SeahorseRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ANGLERFISH.get(), AnglerfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SWORDFISH.get(), SwordfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SUNFISH.get(), SunfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.TUNA.get(), TunaRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MANTA_RAY.get(), MantaRayRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.PENGUIN.get(), PenguinRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BUBBLE.get(), ThrownItemRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CASTAWAY.get(), CastawayRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.DRIFTWOOD_SURFBOARD.get(), DriftwoodSurfboardRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BLOWDART.get(), BlowdartRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.RED_PANDA.get(), RedPandaRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.LEMUR.get(), LemurRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CAPYBARA.get(), CapybaraRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MOTH.get(), MothRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BOAR.get(), BoarRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MOOBLOOM.get(), MoobloomRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BUTTERFLY.get(), ButterflyRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.DEER.get(), DeerRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ULTRAVIOLET_CREAKING.get(), UltravioletCreakingRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BLACKBERRY_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BLACKBERRY_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.BLACKBERRY_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BLACKBERRY_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.GOOSEBERRY_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.GOOSEBERRY_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.STRAWBERRY_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.STRAWBERRY_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.RASPBERRY_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.RASPBERRY_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.GOLDENBERRY_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.GOLDENBERRY_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.GLOW_BERRY_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.GLOW_BERRY_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.SWEET_BERRY_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.SWEET_BERRY_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.GOOSEBERRY_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.GOOSEBERRY_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.STRAWBERRY_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.STRAWBERRY_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.RASPBERRY_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.RASPBERRY_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.GOLDENBERRY_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.GOLDENBERRY_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.GLOW_BERRY_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.GLOW_BERRY_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.SWEET_BERRY_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.SWEET_BERRY_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.SUNSHINE_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.SUNSHINE_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.HOARFROST_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.HOARFROST_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.BLUE_DRIFTWOOD_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BLUE_DRIFTWOOD_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.SUNSHINE_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.SUNSHINE_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.HOARFROST_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.HOARFROST_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.BLUE_DRIFTWOOD_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.BLUE_DRIFTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.WILLOW_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.WILLOW_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.HEARTWOOD_BOAT.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.HEARTWOOD_BOAT_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.WILLOW_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.WILLOW_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.HEARTWOOD_BOAT_WITH_CHEST.get(), context -> new BoatRenderer(context, ZingsBiomesModModels.HEARTWOOD_BOAT_WITH_CHEST_LAYER_LOCATION));
		event.registerEntityRenderer(ZingsBiomesModEntities.LAVA_SQUID.get(), LavaSquidRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ASH_GUARDIAN.get(), AshGuardianRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.FIRE_SALAMANDER.get(), FireSalamanderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SEABUNNY.get(), SeabunnyRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.IGUANA.get(), IguanaRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SCULK_TNT_PRIMED.get(), SculkTNTPrimedRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BOMBERRY_RED.get(), BomberryRedRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BOMBERRY_YELLOW.get(), BomberryYellowRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BOMBERRY_GREEN.get(), BomberryGreenRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BOMBERRY_BLUE.get(), BomberryBlueRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BOMBERRY_PURPLE.get(), BomberryPurpleRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BOMBERRY_WHITE.get(), BomberryWhiteRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.OAK_SLED.get(), OakSledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BIRCH_SLED.get(), BirchSledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.JUNGLE_SLED.get(), JungleSledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ACACIA_SLED.get(), AcaciaSledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.DARK_OAK_SLED.get(), DarkOakSledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MANGROVE_SLED.get(), MangroveSledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CHERRY_SLED.get(), CherrySledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.PALE_OAK_SLED.get(), PaleOakSledRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.OAK_SLED_WITH_CHEST.get(), OakSledWithChestRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BIRCH_SLED_WITH_CHEST.get(), BirchSledWithChestRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SPRUCE_SLED_WITH_CHEST.get(), SpruceSledWithChestRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.JUNGLE_SLED_WITH_CHEST.get(), JungleSledWithChestRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ACACIA_SLED_WITH_CHEST.get(), AcaciaSledWithChestRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.DARK_OAK_SLED_WITH_CHEST.get(), DarkOakSledWithChestRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MANGROVE_SLED_WITH_CHEST.get(), MangroveSledWithChestRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CHERRY_SLED_WITH_CHEST.get(), CherrySledWithChestRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.PALE_OAK_SLED_WITH_CHEST.get(), PaleOakSledWithChestRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.OAK_LOG_FLUME.get(), OakLogFlumeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BIRCH_LOG_FLUME.get(), BirchLogFlumeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.JUNGLE_LOG_FLUME.get(), JungleLogFlumeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ACACIA_LOG_FLUME.get(), AcaciaLogFlumeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.DARK_OAK_LOG_FLUME.get(), DarkOakLogFlumeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MANGROVE_LOG_FLUME.get(), MangroveLogFlumeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CHERRY_LOG_FLUME.get(), CherryLogFlumeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.PALE_OAK_LOG_FLUME.get(), PaleOakLogFlumeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ARROW_BLUE_APATITE.get(), ArrowBlueApatiteRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.TUFF_GOLEM.get(), TuffGolemRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.GLARE.get(), GlareRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SAND_WITCH.get(), SandWitchRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SCORCHED_OSTRICH.get(), ScorchedOstrichRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.AZALEA_WOODEN_BIRDZING.get(), AzaleaWoodenBirdzingRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.END_WOODEN_BIRDZING.get(), EndWoodenBirdzingRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BALD_WOODEN_BIRDZING.get(), BaldWoodenBirdzingRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.REDSTONE_BUG.get(), RedstoneBugRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CRYSTALFISH.get(), CrystalfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ICEFISH.get(), IcefishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.LAVAFISH.get(), LavafishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.FLOODFISH.get(), FloodfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.FUNGIFISH.get(), FungifishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SCULKFISH.get(), SculkfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.MOSSIVERFISH.get(), MossiverfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.DRIPPERFISH.get(), DripperfishRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BLEATSHROOM.get(), BleatshroomRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BLEATSHROOM_SPIT.get(), BleatshroomSpitRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SPOREEPER.get(), SporeeperRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SHRIEKER.get(), ShriekerRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CREAKER.get(), CreakerRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SPIDERSHROOM.get(), SpidershroomRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.EMBER_SKULL.get(), EmberSkullRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.EMBER_WITHER.get(), EmberWitherRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BONE_SPIDER.get(), BoneSpiderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.WAVES.get(), WavesRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.GRAZE.get(), GrazeRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.KOI.get(), KoiRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.TROUT.get(), TroutRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ULTRABBIT.get(), UltrabbitRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CREAK_SPIDER.get(), CreakSpiderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SUN_SPIDER.get(), SunSpiderRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.BADGER.get(), BadgerRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.ENDER_MOTH.get(), EnderMothRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.SPRINGTAIL.get(), SpringtailRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.CHORUS_SNAIL.get(), ChorusSnailRenderer::new);
		event.registerEntityRenderer(ZingsBiomesModEntities.END_CUBE.get(), EndCubeRenderer::new);
	}
}